import { sidebar } from "vuepress-theme-hope";

export const zhSidebarConfig = sidebar({
  "/guide/": [
    {
      text: "基础文档",
      collapsible: true,
      children: [
        "",
        "insert",
        "delete",
        "update",
        "insert-or-update",
        "entity-attribute",
        "navigate-attribute",
        "type-mapping",
      ],
    },
    {
      text: "查询 ✨",
      collapsible: true,
      children: [
        "select",
        "paging",
        "select-single-table",
        "select-multi-table",
        "withtempquery",
        "unionall",
        "select-group-by",
        "select-return-data",
        "select-lazy-loading",
        "select-include",
        "select-as-tree",
        "linq-to-sql",
      ],
    },
    {
      text: "Repository ✨",
      collapsible: true,
      children: [
        "repository",
        "unit-of-work",
        "cascade-saving",
        "cascade-delete",
        "unitofwork-manager",
        "aggregateroot",
      ],
    },
    {
      text: "数据库驱动",
      collapsible: true,
      children: [
        "freesql-provider-custom",
        "freesql-provider-mysqlconnector",
        "freesql-provider-postgresql",
        "freesql-provider-sqlitecore",
        "freesql-provider-oracle",
        "freesql-provider-sqlserver",
        "freesql-provider-odbc",
        "freesql-provider-clickhouse",
        "freesql-provider-questdb",
        "freesql-provider-firebird",
        "freesql-provider-duckdb",
        "freesql-provider-tdengine",
      ],
    },
    "expression-function",
    "transaction",
    "filters",
    "ado",
    "aop",
    {
      text: "CodeFirst",
      collapsible: true,
      children: ["code-first", "fluent-api"],
    },
    "db-first",
    "more",
    {
      text: "高级功能",
      collapsible: true,
      children: [
        "read-write-splitting",
        "sharding",
        "multi-tenancy",
        "performance",
        "dynamic",
        "lowcode",
      ],
    },
    {
      text: "其他作品",
      collapsible: true,
      children: [
        "freeredis",
        "freescheduler",
        "freeim",
        "AdminBlazor",
        "otherworks",
      ],
    },
  ],
  "/reference/": [
    {
      text: "参考",
      collapsible: true,
      icon: "book",
      prefix: "/reference/",
      link: "api",
      children: [
        {
          text: "参考",
          icon: "book",
          children: ["api", "change-log", "vs-dapper", "vs-entity-framework"],
        },
        {
          text: "学习与交流",
          icon: "comment",
          children: ["faq", "donation", "awesome-freesql"],
        },
        {
          text: "扩展",
          icon: "share",
          prefix: "/extra/",
          children: [
            "",
            "freesql-cap",
            "idlebus-freesql",
            "iselect-depcopy",
            "freesql-extensions-baseentity",
            "freesql-auditlog",
            "freesql-docker",
            "issues-mysql5_5",
            "issues-expression-groupbysum",
            "aop-freesql-autofac",
          ],
        },
      ],
    },
    {
      text: "捐赠",
      icon: "hand-holding-dollar",
      link: "service-support",
    },
  ],
});
