name: Publish 

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'

            - name: Setup Elm
              run: |
                  npm install
                  npm run docs:build
              
            - name: GitHub Pages action💕
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN  }}
                cname: 2881099/FreeSql.Wiki.VuePress.github.io
                publish_dir: docs/.vuepress/dist
